name: Build And Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: ${{ runner.os }} ${{ matrix.compiler_name }} ${{ matrix.build_type }} Build
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        build_type: [Debug, Release]
        compiler: [gcc, clang]
        include:
          - compiler: gcc
            cxx_compiler: g++
            compiler_name: GCC
          - compiler: clang
            cxx_compiler: clang++
            compiler_name: Clang
        exclude:
          - os: windows-latest
            compiler: gcc
          - os: ubuntu-latest
            compiler: clang

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          cache: 'pip'

      - name: Setup Python Dependencies
        run: pip install -r requirements.txt

      - name: Setup Ninja
        uses: ashutoshvarma/setup-ninja@master
        with:
          version: 1.10.0

      - name: Add clang path to $PATH env on Windows
        shell: bash
        if: ${{ (runner.os == 'Windows') && (matrix.compiler == 'clang') }}
        run: echo "PATH=$PATH:C:\msys64\mingw64\bin" >> $GITHUB_ENV

      - name: Configure CMake
        env:
          CC: ${{ matrix.compiler }}
          CXX: ${{ matrix.cxx_compiler }}
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DCMAKE_CXX_STANDARD=20 -G Ninja

      - name: Build
        # Build your program with the given configuration
        run: cmake --build ${{github.workspace}}/build --config ${{ matrix.build_type }}

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ctest -C ${{ matrix.build_type}}
